/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_1$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_2$schema = z.string()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_3$schema = z.string()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_4$schema = z.string()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_result$schema = z.object({
  'accepted': z.boolean(),
  'reason': z.string().optional(),
})
const _deepseek_ai_dsh_page_app_manager_pageAppManager_installPackage_parameter_0$schema = z.object({
  'kind': z.union([z.literal("file"), z.literal("registry"), z.literal("link"), z.literal("tarball"), z.literal("git")]).readonly(),
  'spec': z.string().readonly(),
  'display': z.object({
  'kind': z.union([z.literal("file"), z.literal("registry"), z.literal("link"), z.literal("tarball"), z.literal("git")]).readonly(),
  'display': z.string().readonly(),
}).readonly(),
})
const _deepseek_ai_dsh_page_app_manager_pageAppManager_installPackage_parameter_1$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_page_app_manager_pageAppManager_installPackage_result$schema = z.number()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_list_result$schema = z.object({
  'profile': z.object({
  'name': z.string().readonly(),
  'directory': z.string().readonly(),
}).readonly(),
  'revision': z.number().readonly(),
  'entries': z.array(z.object({
  'packageName': z.string().readonly(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("registry"), z.literal("link"), z.literal("tarball"), z.literal("git")]).readonly(),
  'display': z.string().readonly(),
}).readonly(),
  'resolvedVersion': z.string().readonly(),
  'page': z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'defaultOrder': z.number().readonly(),
  'rootEntryId': z.string().readonly(),
}).readonly(),
  'order': z.number().readonly(),
  'enabled': z.boolean().readonly(),
  'hidden': z.boolean().readonly(),
  'installedAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'health': z.union([z.literal("ready"), z.literal("disabled"), z.literal("missing-dependency"), z.literal("version-drift"), z.literal("invalid-manifest"), z.literal("missing-manager"), z.literal("activation-failed"), z.literal("externally-overridden"), z.literal("recovery-required")]).readonly(),
  'runtimeState': z.union([z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly().optional(),
  'lastError': z.string().readonly().optional(),
})).readonly(),
  'operation': z.union([z.literal(null), z.object({
  'state': z.union([z.literal("active"), z.literal("recovery-required"), z.literal("installing"), z.literal("removing"), z.literal("install-failed"), z.literal("remove-failed")]).readonly(),
  'phase': z.union([z.literal("prepared"), z.literal("staged"), z.literal("committing")]).readonly().optional(),
})]).readonly(),
  'recovery': z.union([z.literal(null), z.object({
  'message': z.string().readonly(),
})]).readonly(),
})
const _deepseek_ai_dsh_page_app_manager_pageAppManager_recover_result$schema = z.object({
  'action': z.string(),
  'message': z.string().optional(),
})
const _deepseek_ai_dsh_page_app_manager_pageAppManager_reorder_parameter_0$schema = z.array(z.string())
const _deepseek_ai_dsh_page_app_manager_pageAppManager_reorder_result$schema = z.number()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_setEnabled_parameter_0$schema = z.string()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_setEnabled_parameter_1$schema = z.boolean()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_setEnabled_result$schema = z.number()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_setHidden_parameter_0$schema = z.string()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_setHidden_parameter_1$schema = z.boolean()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_setHidden_result$schema = z.number()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_uninstall_parameter_0$schema = z.string()
const _deepseek_ai_dsh_page_app_manager_pageAppManager_uninstall_result$schema = z.number()

export const TYPERT = {
  package: '@deepseek-ai/dsh-page-app-manager',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-page-app-manager#pageAppManager/ackClientActivation',
      service: 'pageAppManager',
      namespace: 'pageAppManager',
      method: 'ackClientActivation',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'transactionId',
          wire: 'transactionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager/types#PageAppTransactionId',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_0$schema,
          },
        },
        {
          name: 'clientInstanceId',
          wire: 'clientInstanceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager/types#PageAppClientInstanceId',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_1$schema,
          },
        },
        {
          name: 'packageName',
          wire: 'packageName',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/ackClientActivation:packageName',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_2$schema,
          },
        },
        {
          name: 'pageId',
          wire: 'pageId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/ackClientActivation:pageId',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_3$schema,
          },
        },
        {
          name: 'graphRevision',
          wire: 'graphRevision',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/ackClientActivation:graphRevision',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_parameter_4$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/ackClientActivation:result',
        schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_ackClientActivation_result$schema,
      },
      sourceLocation: {"file":"packages/host/page-app-manager/src/index.ts","line":261,"column":10},
    },
    {
      id: '@deepseek-ai/dsh-page-app-manager#pageAppManager/installPackage',
      service: 'pageAppManager',
      namespace: 'pageAppManager',
      method: 'installPackage',
      implementation: 'install',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'source',
          wire: 'source',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager/types#PageAppInstallSource',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_installPackage_parameter_0$schema,
          },
        },
        {
          name: 'clientInstanceId',
          wire: 'clientInstanceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager/types#PageAppClientInstanceId',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_installPackage_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/installPackage:result',
        schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_installPackage_result$schema,
      },
      sourceLocation: {"file":"packages/host/page-app-manager/src/index.ts","line":202,"column":10},
    },
    {
      id: '@deepseek-ai/dsh-page-app-manager#pageAppManager/list',
      service: 'pageAppManager',
      namespace: 'pageAppManager',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-page-app-manager/types#PageAppManagerSnapshot',
        schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_list_result$schema,
      },
      sourceLocation: {"file":"packages/host/page-app-manager/src/index.ts","line":187,"column":10},
    },
    {
      id: '@deepseek-ai/dsh-page-app-manager#pageAppManager/recover',
      service: 'pageAppManager',
      namespace: 'pageAppManager',
      method: 'recover',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/recover:result',
        schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_recover_result$schema,
      },
      sourceLocation: {"file":"packages/host/page-app-manager/src/index.ts","line":279,"column":10},
    },
    {
      id: '@deepseek-ai/dsh-page-app-manager#pageAppManager/reorder',
      service: 'pageAppManager',
      namespace: 'pageAppManager',
      method: 'reorder',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'pageIds',
          wire: 'pageIds',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/reorder:pageIds',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_reorder_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/reorder:result',
        schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_reorder_result$schema,
      },
      sourceLocation: {"file":"packages/host/page-app-manager/src/index.ts","line":235,"column":10},
    },
    {
      id: '@deepseek-ai/dsh-page-app-manager#pageAppManager/setEnabled',
      service: 'pageAppManager',
      namespace: 'pageAppManager',
      method: 'setEnabled',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'pageId',
          wire: 'pageId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/setEnabled:pageId',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_setEnabled_parameter_0$schema,
          },
        },
        {
          name: 'enabled',
          wire: 'enabled',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/setEnabled:enabled',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_setEnabled_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/setEnabled:result',
        schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_setEnabled_result$schema,
      },
      sourceLocation: {"file":"packages/host/page-app-manager/src/index.ts","line":214,"column":10},
    },
    {
      id: '@deepseek-ai/dsh-page-app-manager#pageAppManager/setHidden',
      service: 'pageAppManager',
      namespace: 'pageAppManager',
      method: 'setHidden',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'pageId',
          wire: 'pageId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/setHidden:pageId',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_setHidden_parameter_0$schema,
          },
        },
        {
          name: 'hidden',
          wire: 'hidden',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/setHidden:hidden',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_setHidden_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/setHidden:result',
        schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_setHidden_result$schema,
      },
      sourceLocation: {"file":"packages/host/page-app-manager/src/index.ts","line":225,"column":10},
    },
    {
      id: '@deepseek-ai/dsh-page-app-manager#pageAppManager/uninstall',
      service: 'pageAppManager',
      namespace: 'pageAppManager',
      method: 'uninstall',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'pageId',
          wire: 'pageId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/uninstall:pageId',
            schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_uninstall_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-page-app-manager#pageAppManager/uninstall:result',
        schema: _deepseek_ai_dsh_page_app_manager_pageAppManager_uninstall_result$schema,
      },
      sourceLocation: {"file":"packages/host/page-app-manager/src/index.ts","line":246,"column":10},
    },
  ],
  model: {
    "services": [
      {
        "description": "Build the Host page-app manager service. Extends `TypertRemoteService` so the generated `pageAppManager` namespace exposes the mutation API; the read projection and staged validation are plain methods on the same service.",
        "summary": "Build the Host page-app manager service.",
        "tags": [
          {
            "name": "param",
            "argument": "ctx",
            "comment": "- plugin context with the Loader available.",
            "text": "@param ctx - plugin context with the Loader available.\n *"
          },
          {
            "name": "param",
            "argument": "options",
            "comment": "- the launcher-provided profile runtime (identity source).",
            "text": "@param options - the launcher-provided profile runtime (identity source)."
          }
        ],
        "jsDoc": "/**\n * Build the Host page-app manager service. Extends `TypertRemoteService` so the\n * generated `pageAppManager` namespace exposes the mutation API; the read\n * projection and staged validation are plain methods on the same service.\n * @param ctx - plugin context with the Loader available.\n * @param options - the launcher-provided profile runtime (identity source).\n */",
        "key": "pageAppManager",
        "exportName": "PageAppManager",
        "members": [
          {
            "kind": "getter",
            "name": "identity",
            "signature": "public get identity(): { name: string; directory: string }",
            "summary": "The immutable active-profile identity (consumers cannot replace it).",
            "jsDoc": "/** The immutable active-profile identity (consumers cannot replace it). */"
          },
          {
            "kind": "getter",
            "name": "activation",
            "signature": "public get activation(): PageAppLifecycle['activation']",
            "summary": "The pending targeted client activation gate (install acknowledgement).",
            "jsDoc": "/** The pending targeted client activation gate (install acknowledgement). */"
          },
          {
            "kind": "method",
            "name": "dispose",
            "signature": "public dispose(): void",
            "summary": "Abort the in-flight transaction; wired to the manager fiber's effect.",
            "jsDoc": "/** Abort the in-flight transaction; wired to the manager fiber's effect. */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') public list(): PageAppManagerSnapshot",
            "summary": "The full read-only projection of the managed set.",
            "jsDoc": "/**\n * The full read-only projection of the managed set. The registry is the\n * ownership authority; health is derived from current dependency, version,\n * and runtime facts. Plugin Inventory and unrelated Loader rows never create\n * entries.\n * @returns the immutable snapshot.\n */"
          },
          {
            "kind": "method",
            "name": "install",
            "signature": "@Remote('installPackage') public install(source: PageAppInstallSource, clientInstanceId: PageAppClientInstanceId, signal: AbortSignal): Promise<number>",
            "summary": "Install one managed package (exposed as the `installPackage` Remote of the Settings add-flow; the gateway namespace service reserves the `install` member on its prototype, so the wire method cannot reuse that spelling while the internal lifecycle method keeps the `install` name).",
            "jsDoc": "/**\n * Install one managed package (exposed as the `installPackage` Remote of the\n * Settings add-flow; the gateway namespace service reserves the `install`\n * member on its prototype, so the wire method cannot reuse that spelling\n * while the internal lifecycle method keeps the `install` name).\n * @param source - the validated install source.\n * @param clientInstanceId - the opaque initiating client instance.\n * @param signal - cancellation; aborts pnpm and the activation wait.\n * @returns the committed registry revision.\n */"
          },
          {
            "kind": "method",
            "name": "setEnabled",
            "signature": "@Remote('setEnabled') public setEnabled(pageId: string, enabled: boolean, signal: AbortSignal): Promise<number>",
            "summary": "Enable or disable one managed page.",
            "jsDoc": "/**\n * Enable or disable one managed page.\n * @param pageId - the managed page id.\n * @param enabled - the new enabled state.\n * @param signal - cancellation; honored by the shared lock.\n * @returns the committed registry revision.\n */"
          },
          {
            "kind": "method",
            "name": "setHidden",
            "signature": "@Remote('setHidden') public setHidden(pageId: string, hidden: boolean): Promise<number>",
            "summary": "Hide or show one managed page (presentation only).",
            "jsDoc": "/**\n * Hide or show one managed page (presentation only).\n * @param pageId - the managed page id.\n * @param hidden - the new hidden state.\n * @returns the committed registry revision.\n */"
          },
          {
            "kind": "method",
            "name": "reorder",
            "signature": "@Remote('reorder') public reorder(pageIds: readonly string[]): Promise<number>",
            "summary": "Reorder managed pages.",
            "jsDoc": "/**\n * Reorder managed pages.\n * @param pageIds - page ids in the desired order.\n * @returns the committed registry revision.\n */"
          },
          {
            "kind": "method",
            "name": "uninstall",
            "signature": "@Remote('uninstall') public uninstall(pageId: string, signal: AbortSignal): Promise<number>",
            "summary": "Uninstall one managed page from the current profile.",
            "jsDoc": "/**\n * Uninstall one managed page from the current profile.\n * @param pageId - the managed page id.\n * @param signal - cancellation; aborts pnpm and the activation wait.\n * @returns the committed registry revision.\n */"
          },
          {
            "kind": "method",
            "name": "ackClientActivation",
            "signature": "@Remote('ackClientActivation') public ackClientActivation( transactionId: PageAppTransactionId, clientInstanceId: PageAppClientInstanceId, packageName: string, pageId: string, graphRevision: string, ): { accepted: boolean; reason?: string }",
            "summary": "Acknowledge a pending targeted client activation.",
            "jsDoc": "/**\n * Acknowledge a pending targeted client activation. Only the first valid\n * acknowledgement from the initiating client instance settles the install.\n * @param transactionId - the transaction the acknowledgement names.\n * @param clientInstanceId - the acknowledging client instance.\n * @param packageName - the acknowledged package.\n * @param pageId - the acknowledged page id.\n * @param graphRevision - the graph revision the client converged to.\n * @returns whether this attempt settled the transaction.\n */"
          },
          {
            "kind": "method",
            "name": "recover",
            "signature": "@Remote('recover') public recover(): Promise<{ action: string; message?: string }>",
            "summary": "Run the startup/operator recovery over the profile journal.",
            "jsDoc": "/**\n * Run the startup/operator recovery over the profile journal.\n * @returns the recovery outcome.\n */"
          },
          {
            "kind": "method",
            "name": "snapshot",
            "signature": "public snapshot(): PageAppManagerSnapshot",
            "summary": "The full read-only projection of the managed set (the `list` Remote delegates here; the raw method stays available to host-side consumers).",
            "jsDoc": "/**\n * The full read-only projection of the managed set (the `list` Remote\n * delegates here; the raw method stays available to host-side consumers).\n * @returns the immutable snapshot.\n */"
          },
          {
            "kind": "method",
            "name": "validateInstall",
            "signature": "public validateInstall(source: string | PageAppInstallSource): { source: PageAppInstallSource; preflight: string | null }",
            "summary": "Parse and classify one Settings add-flow source spec.",
            "jsDoc": "/**\n * Parse and classify one Settings add-flow source spec. Local directory\n * sources are additionally preflighted against the on-disk package; registry,\n * git, link, and tarball sources await the pnpm staging step (Task 8) before\n * the full static validation runs. Never mutates ownership.\n * @param source - the raw specifier (or an already-typed source).\n * @returns the validated install source plus a preflight note.\n * @throws {Error} when the spec is rejected (kind grammar, credentials, relative path).\n */"
          }
        ],
        "types": [
          {
            "name": "ActivationAcknowledgement",
            "declaration": "export interface ActivationAcknowledgement {\n    readonly accepted: boolean;\n    readonly reason?: 'stale' | 'wrong-client' | 'wrong-target' | 'already-settled';\n}"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "ClientActivationRequest",
            "declaration": "export interface ClientActivationRequest {\n    readonly transactionId: PageAppTransactionId;\n    readonly clientInstanceId: PageAppClientInstanceId;\n    readonly packageName: string;\n    readonly pageId: string;\n    readonly graphRevision: string;\n}"
          },
          {
            "name": "PageAppActivationGate",
            "declaration": "export class PageAppActivationGate {\n    get pending(): boolean;\n    get pendingRequest(): ClientActivationRequest | undefined;\n    open(request: ClientActivationRequest): void;\n    awaitSettlement(signal: AbortSignal, timeoutMs: number): Promise<ClientActivationRequest>;\n    acknowledge(transactionId: PageAppTransactionId, clientInstanceId: PageAppClientInstanceId, packageName: string, pageId: string, graphRevision: string): ActivationAcknowledgement;\n    discard(): void;\n}"
          },
          {
            "name": "PageAppClientInstanceId",
            "declaration": "export type PageAppClientInstanceId = Branded<'PageAppClientInstanceId'>;"
          },
          {
            "name": "PageAppHealth",
            "declaration": "export type PageAppHealth = 'ready' | 'disabled' | 'missing-dependency' | 'version-drift' | 'invalid-manifest' | 'missing-manager' | 'activation-failed' | 'externally-overridden' | 'recovery-required';"
          },
          {
            "name": "PageAppInstallSource",
            "declaration": "export interface PageAppInstallSource {\n    readonly kind: PageAppSourceKind;\n    readonly spec: string;\n    readonly display: PageAppRegistrySource;\n}"
          },
          {
            "name": "PageAppJournalPhase",
            "declaration": "export type PageAppJournalPhase = 'prepared' | 'staged' | 'committing';"
          },
          {
            "name": "PageAppLifecycle",
            "declaration": "export class PageAppLifecycle {\n    get activation(): PageAppActivationGate;\n    dispose(): void;\n    install(source: PageAppInstallSource, clientInstanceId: PageAppClientInstanceId, signal: AbortSignal): Promise<number>;\n    setEnabled(pageId: string, enabled: boolean, signal: AbortSignal): Promise<number>;\n    setHidden(pageId: string, hidden: boolean): Promise<number>;\n    reorder(pageIds: readonly string[]): Promise<number>;\n    uninstall(pageId: string, signal: AbortSignal): Promise<number>;\n}"
          },
          {
            "name": "PageAppManagerSnapshot",
            "declaration": "export interface PageAppManagerSnapshot {\n    readonly profile: PageAppProfileIdentity;\n    readonly revision: number;\n    readonly entries: readonly PageAppView[];\n    readonly operation: PageAppOperationView | null;\n    readonly recovery: PageAppRecoveryView | null;\n}"
          },
          {
            "name": "PageAppOperationState",
            "declaration": "export type PageAppOperationState = 'installing' | 'active' | 'removing' | 'install-failed' | 'remove-failed' | 'recovery-required';"
          },
          {
            "name": "PageAppOperationView",
            "declaration": "export interface PageAppOperationView {\n    readonly state: PageAppOperationState;\n    readonly phase?: PageAppJournalPhase;\n}"
          },
          {
            "name": "PageAppPageFields",
            "declaration": "export interface PageAppPageFields {\n    readonly id: string;\n    readonly name: string;\n    readonly description: string;\n    readonly defaultOrder: number;\n    readonly rootEntryId: string;\n}"
          },
          {
            "name": "PageAppProfileIdentity",
            "declaration": "export interface PageAppProfileIdentity {\n    readonly name: string;\n    readonly directory: string;\n}"
          },
          {
            "name": "PageAppRecoveryView",
            "declaration": "export interface PageAppRecoveryView {\n    readonly message: string;\n}"
          },
          {
            "name": "PageAppRegistrySource",
            "declaration": "export interface PageAppRegistrySource {\n    readonly kind: PageAppSourceKind;\n    readonly display: string;\n}"
          },
          {
            "name": "PageAppRuntimeStateLabel",
            "declaration": "export type PageAppRuntimeStateLabel = 'pending' | 'loading' | 'active' | 'failed' | 'unloading';"
          },
          {
            "name": "PageAppSourceKind",
            "declaration": "export type PageAppSourceKind = 'registry' | 'file' | 'link' | 'tarball' | 'git';"
          },
          {
            "name": "PageAppTransactionId",
            "declaration": "export type PageAppTransactionId = Branded<'PageAppTransactionId'>;"
          },
          {
            "name": "PageAppView",
            "declaration": "export interface PageAppView {\n    readonly packageName: string;\n    readonly source: PageAppRegistrySource;\n    readonly resolvedVersion: string;\n    readonly page: PageAppPageFields;\n    readonly order: number;\n    readonly enabled: boolean;\n    readonly hidden: boolean;\n    readonly installedAt: string;\n    readonly updatedAt: string;\n    readonly health: PageAppHealth;\n    readonly runtimeState?: PageAppRuntimeStateLabel;\n    readonly lastError?: string;\n}"
          }
        ]
      },
      {
        "description": "The Feature-facing domain API the manager provides.",
        "summary": "The Feature-facing domain API the manager provides.",
        "tags": [],
        "jsDoc": "/** The Feature-facing domain API the manager provides. */",
        "key": "workbenchRuntime",
        "exportName": "WorkbenchRuntime",
        "members": [
          {
            "kind": "property",
            "name": "lifecycle",
            "signature": "readonly lifecycle: { /** * Register one disposal callback that runs when the runtime fiber unloads. * @param callback - the callback to run at disposal. * @returns a disposer that removes the callback. */ onDispose(callback: () => void): () => void }",
            "summary": "Lifecycle disposal: every side effect a Feature registers releases with the runtime.",
            "jsDoc": "/** Lifecycle disposal: every side effect a Feature registers releases with the runtime. */"
          },
          {
            "kind": "property",
            "name": "surfaces",
            "signature": "readonly surfaces: { /** * Register one workspace surface seat. The returned disposer removes the * registration; the runtime records the owning package provenance. * @param registration - page id, owning package, and the surface render. * @returns a disposer that removes the registration. */ registerWorkspaceSurface(registration: WorkbenchSurfaceRegistration): () => void /** Every live surface registration, in registration order. */ list(): readonly WorkbenchSurfaceRegistration[] }",
            "summary": "Workspace-surface registration: the contract's single surface entry.",
            "jsDoc": "/** Workspace-surface registration: the contract's single surface entry. */"
          },
          {
            "kind": "property",
            "name": "events",
            "signature": "readonly events: WorkbenchEventSubscription",
            "summary": "Runtime events: the Feature subscribes through the contract, never Cordis.",
            "jsDoc": "/** Runtime events: the Feature subscribes through the contract, never Cordis. */"
          },
          {
            "kind": "property",
            "name": "storage",
            "signature": "readonly storage: { /** Read one stored value (undefined when absent). */ get(key: string): unknown /** Store one value under a key. */ set(key: string, value: unknown): void }",
            "summary": "Keyed storage the runtime owns per fiber.",
            "jsDoc": "/** Keyed storage the runtime owns per fiber. */"
          },
          {
            "kind": "property",
            "name": "host",
            "signature": "readonly host: { /** * Call one Host capability. Contract v1 keeps the seam but wires no * capability yet: the fixture migration (M9) registers the surface * lifecycle behind this face, so an unknown method fails loud instead of * silently no-oping. * @param method - the capability name. * @param args - the capability arguments. * @returns the capability result. * @throws {Error} naming the unwired method. */ call(method: string, ...args: unknown[]): Promise<unknown> }",
            "summary": "Host call seam: the Feature invokes Host capabilities by name.",
            "jsDoc": "/** Host call seam: the Feature invokes Host capabilities by name. */"
          }
        ],
        "types": [
          {
            "name": "WorkbenchEventSubscription",
            "declaration": "export interface WorkbenchEventSubscription {\n    on(name: string, listener: (payload: unknown) => void): () => void;\n    emit(name: string, payload?: unknown): void;\n}"
          },
          {
            "name": "WorkbenchSurfaceRegistration",
            "declaration": "export interface WorkbenchSurfaceRegistration {\n    readonly pageId: string;\n    readonly packageName: string;\n    readonly render?: unknown;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "An install staged its runtime layer and now waits for the targeted client instance to acknowledge the activation.",
        "summary": "An install staged its runtime layer and now waits for the targeted client instance to acknowledge the activation.",
        "tags": [
          {
            "name": "param",
            "argument": "request",
            "comment": "- transaction, client instance, package, page, and graph revision.",
            "text": "@param request - transaction, client instance, package, page, and graph revision.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * An install staged its runtime layer and now waits for the targeted\n * client instance to acknowledge the activation.\n * @param request - transaction, client instance, package, page, and graph revision.\n * @mode emit\n */",
        "name": "page-app-manager/activation-requested",
        "mode": "emit",
        "signature": "'page-app-manager/activation-requested'(request: PageAppActivationRequestedEvent): void"
      },
      {
        "description": "The manager committed a registry change (install/enable/disable/hide/ reorder/uninstall published a new revision). Consumers re-read the snapshot.",
        "summary": "The manager committed a registry change (install/enable/disable/hide/ reorder/uninstall published a new revision).",
        "tags": [
          {
            "name": "param",
            "argument": "revision",
            "comment": "- the newly committed registry revision.",
            "text": "@param revision - the newly committed registry revision.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * The manager committed a registry change (install/enable/disable/hide/\n * reorder/uninstall published a new revision). Consumers re-read the\n * snapshot.\n * @param revision - the newly committed registry revision.\n * @mode emit\n */",
        "name": "page-app-manager/changed",
        "mode": "emit",
        "signature": "'page-app-manager/changed'(revision: number): void"
      }
    ],
    "objects": []
  },
}
