/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { PageAppClientInstanceId, PageAppInstallSource, PageAppManagerSnapshot, PageAppTransactionId } from '@deepseek-ai/dsh-page-app-manager/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706167654170704d616e61676572 {
    ackClientActivation: (transactionId: PageAppTransactionId, clientInstanceId: PageAppClientInstanceId, packageName: string, pageId: string, graphRevision: string) => Promise<RemoteResult<{ accepted: boolean; reason?: string; }>>
    installPackage: (source: PageAppInstallSource, clientInstanceId: PageAppClientInstanceId, signal?: AbortSignal) => Promise<RemoteResult<number>>
    list: () => Promise<RemoteResult<PageAppManagerSnapshot>>
    recover: () => Promise<RemoteResult<{ action: string; message?: string; }>>
    reorder: (pageIds: readonly string[]) => Promise<RemoteResult<number>>
    setEnabled: (pageId: string, enabled: boolean, signal?: AbortSignal) => Promise<RemoteResult<number>>
    setHidden: (pageId: string, hidden: boolean) => Promise<RemoteResult<number>>
    uninstall: (pageId: string, signal?: AbortSignal) => Promise<RemoteResult<number>>
  }
  interface TypertRemoteMap {
    'pageAppManager/ackClientActivation': (transactionId: PageAppTransactionId, clientInstanceId: PageAppClientInstanceId, packageName: string, pageId: string, graphRevision: string) => Promise<RemoteResult<{ accepted: boolean; reason?: string; }>>
    'pageAppManager/installPackage': (source: PageAppInstallSource, clientInstanceId: PageAppClientInstanceId, signal?: AbortSignal) => Promise<RemoteResult<number>>
    'pageAppManager/list': () => Promise<RemoteResult<PageAppManagerSnapshot>>
    'pageAppManager/recover': () => Promise<RemoteResult<{ action: string; message?: string; }>>
    'pageAppManager/reorder': (pageIds: readonly string[]) => Promise<RemoteResult<number>>
    'pageAppManager/setEnabled': (pageId: string, enabled: boolean, signal?: AbortSignal) => Promise<RemoteResult<number>>
    'pageAppManager/setHidden': (pageId: string, hidden: boolean) => Promise<RemoteResult<number>>
    'pageAppManager/uninstall': (pageId: string, signal?: AbortSignal) => Promise<RemoteResult<number>>
  }
  interface TypertRemoteNamespaceMap {
    'pageAppManager': TypertRemoteNamespace$706167654170704d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
